### ISSUE TITLE
Error ELIFECYCLE on installing

### ISSUE THREAD

**Issue by pabloab** [oldrich-s/musicope#34]
I get this errors:

    $ npm start
    events.js:167
          throw er; // Unhandled 'error' event
          ^
    Error: listen EACCES 0.0.0.0:80
        at Server.setupListenHandle [as _listen2] (net.js:1269:19)
        at listenInCluster (net.js:1334:12)
        at Server.listen (net.js:1421:7)
        at Function.listen (/tmp/musicope/node_modules/express/lib/application.js:618:24)
        at Object.<anonymous> (/tmp/musicope/server.js:72:8)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    Emitted 'error' event at:
        at emitErrorNT (net.js:1313:8)
        at process._tickCallback (internal/process/next_tick.js:63:19)
        at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
        at startup (internal/bootstrap/node.js:279:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! musicope@3.0.0 start: `node server.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the musicope@3.0.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/pablo/.npm/_logs/2019-04-01T06_41_16_689Z-debug.log

    $ inxi -S -! 31 
    System:    Kernel: 4.15.0-46-generic x86_64 bits: 64 Desktop: Gnome 3.28.3 Distro: Ubuntu 18.04.2 LTS

The log file: [2019-04-01T06_41_16_689Z-debug.log](https://github.com/oldrich-s/musicope/files/3028051/2019-04-01T06_41_16_689Z-debug.log).

Already tried setting with 

    "dependencies": {
      "express": "latest",
      "typescript": "latest"

**Comment by vnadot** [comment]
Try as root
```
$ sudo npm start
```

**Comment by WouterBos** [comment]
I have the same issue, but then on Windows.

**Comment by tuxutku** [comment]
port number should be higher than 1024, change `server.listen('88')` in `server.js` to `server.listen('1069')` etc...
