### ISSUE TITLE
NPM Install Fails - run as root

### ISSUE THREAD

**Issue by zdsklfgh** [oldrich-s/musicope#44]
terminal out

musicope-master# npm start

> musicope@3.0.0 start
> node server.js

node:events:353
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1278:21)
    at listenInCluster (node:net:1343:12)
    at Server.listen (node:net:1429:7)
    at Function.listen (/home/*****/Documents/musicope-master/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/*****/Documents/musicope-master/server.js:72:8)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1322:8)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
npm ERR! code 1
npm ERR! path /home/*****/Documents/musicope-master
npm ERR! command failed
npm ERR! command sh -c node server.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-29T18_44_37_466Z-debug.log

log file

0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/*****/Documents/musicope-master/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session e04fb45a6ff1f9e7
20 timing npm:load Completed in 17ms
21 timing command:run-script Completed in 287ms
22 timing command:start Completed in 289ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:376:20)
23 verbose stack     at maybeClose (node:internal/child_process:1063:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
24 verbose pkgid musicope@3.0.0
25 verbose cwd /home/*****/Documents/musicope-master
26 verbose Linux 5.4.0-58-generic
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v15.5.0
29 verbose npm  v7.3.0
30 error code 1
31 error path /home/*****/Documents/musicope-master
32 error command failed
33 error command sh -c node server.js
34 verbose exit 1

**Comment by qgustavor** [comment]
The port should be configurable somehow and the default set to something else than 80.

**Comment by albfan** [comment]
privileged ports like 80 can only be used with permission.

Something like this:

```
diff --git i/server.js w/server.js
index 9a4425c..d9d67f7 100644
--- i/server.js
+++ w/server.js
@@ -69,4 +69,8 @@ server.use((req, res) => {
     }
 })
 
-server.listen('80')
\ No newline at end of file
+const { argv } = require('yargs');
+let port = argv.port ?? process.env.PORT ?? 80
+
+console.log("listening on port: " + port)
+server.listen(port)
```

should allow to redirect:

```
$ PORT=8080 npm start

> musicope@3.0.0 start
> node server.js

listening on port: 8080
^C


$ PORT=8080 npm start -- --port=8081

> musicope@3.0.0 start
> node server.js --port=8081

listening on port: 8081
^C
```

but definitely default port should be 8080 or some non privileged port
